// Package base provides core C++ structure generation.
package base

import (
	"github.com/aperturerobotics/go-protobuf-cpp-gen/generator/genfile"
	"github.com/aperturerobotics/go-protobuf-cpp-gen/internal/naming"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// GenerateHeaderPreamble generates the header file preamble (comment, guard, etc.).
func GenerateHeaderPreamble(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	guard := naming.HeaderGuard(file.Path())

	g.P("// Generated by protoc-gen-cpp-lite. DO NOT EDIT.")
	g.P("// source: ", file.Path())
	g.P()
	g.P("#ifndef ", guard)
	g.P("#define ", guard)
	g.P()
}

// GenerateHeaderPostamble generates the header file postamble (close guard).
func GenerateHeaderPostamble(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	guard := naming.HeaderGuard(file.Path())
	g.P()
	g.P("#endif  // ", guard)
}

// GenerateSourcePreamble generates the source file preamble.
func GenerateSourcePreamble(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	g.P("// Generated by protoc-gen-cpp-lite. DO NOT EDIT.")
	g.P("// source: ", file.Path())
	g.P()
}

// OpenNamespace opens the C++ namespace for the proto package.
func OpenNamespace(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	pkg := string(file.Package())
	if pkg == "" {
		return
	}

	parts := naming.NamespaceParts(pkg)
	for _, part := range parts {
		g.P("namespace ", part, " {")
	}
	g.P()
}

// CloseNamespace closes the C++ namespace for the proto package.
func CloseNamespace(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	pkg := string(file.Package())
	if pkg == "" {
		return
	}

	parts := naming.NamespaceParts(pkg)
	g.P()
	// Close in reverse order
	for i := len(parts) - 1; i >= 0; i-- {
		g.P("}  // namespace ", parts[i])
	}
}

// GenerateForwardDeclarations generates forward declarations for all messages in the file.
func GenerateForwardDeclarations(g *genfile.GeneratedFile, file protoreflect.FileDescriptor) {
	messages := file.Messages()
	if messages.Len() == 0 {
		return
	}

	g.P("// Forward declarations")
	for i := 0; i < messages.Len(); i++ {
		generateForwardDeclaration(g, messages.Get(i), "")
	}
	g.P()
}

func generateForwardDeclaration(g *genfile.GeneratedFile, msg protoreflect.MessageDescriptor, prefix string) {
	// Skip map entries
	if msg.IsMapEntry() {
		return
	}

	className := naming.ClassName(string(msg.Name()))
	// All messages are at namespace level, so just declare the class
	g.P("class ", className, ";")

	// Handle nested messages - also declared at namespace level
	nested := msg.Messages()
	for i := 0; i < nested.Len(); i++ {
		generateForwardDeclaration(g, nested.Get(i), "")
	}
}

// NamespacePrefix returns the C++ namespace prefix for a file (e.g., "::foo::bar::").
func NamespacePrefix(file protoreflect.FileDescriptor) string {
	pkg := string(file.Package())
	if pkg == "" {
		return "::"
	}
	return "::" + naming.Namespace(pkg) + "::"
}

// FullyQualifiedClassName returns the fully qualified C++ class name for a message.
// Since we generate all messages at namespace level (not as nested classes),
// we use just the namespace and class name without parent class names.
func FullyQualifiedClassName(msg protoreflect.MessageDescriptor) string {
	className := naming.ClassName(string(msg.Name()))

	// Get the file for namespace
	file := msg.ParentFile()
	pkg := string(file.Package())

	if pkg == "" {
		return "::" + className
	}
	return "::" + naming.Namespace(pkg) + "::" + className
}
